name: docker-build-stage-ci
on:
  pull_request:
        
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_NAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: Set current datetime as env variable
        env:
          TZ: 'Asia/Tokyo'
        run: echo "BUILD_DATETIME=$(date +'%Y-%m-%d_%H-%M')" >> $GITHUB_ENV
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.prod
          platforms: linux/amd64 #,linux/arm64
          # cache-from: type=gha
          # cache-to: type=gha,mode=max
          # no-cache: ${{ inputs.disable-cache == true }}
          push: false
          tags: |
            ${{ secrets.DOCKERHUB_USER }}/rem:${{ env.BUILD_DATETIME }}
            ${{ secrets.DOCKERHUB_USERNAME }}/rem:latest
      # -
      #   name: discord notification
      #   uses: docker://alicey/gha2discord:latest
      #   env:
      #       WEBHOOK_URL: ${{ secrets.DC_WEBHOOK_URL }}
      #       MESSAGE_USERNAME: "GitHub Actions"
      #       MESSAGE_AVATAR_URL: ""
      #       MESSAGE_AUTHORNAME: "rem Docker Push"
      #       MESSAGE_AUTHORICON_URL: ""
      #       MESSAGE_COMMENT: "Image:\n${{ secrets.DOCKERHUB_USER }}/rem:${{ env.BUILD_DATETIME }}"
      #   with:
      #       entrypoint: "python3"
      #       args: "/opt/app/app.py"